#!/usr/bin/env python3
"""
Create instructions for manual video creation
"""

import aiofiles
import logging
import os
import tempfile
from datetime import datetime


async def create_manual_video_instructions(prompt: str) -> None:
    """Create a markdown file with manual video creation steps."""
    logger = logging.getLogger(__name__)
    try:
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        instructions_file = f"manual_video_instructions_{timestamp}.md"
        instructions = f"""# Manual Video Creation Instructions

**Generated on:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
**Original Prompt:** {prompt}

## 🎬 Create Video Manually

### Option 1: Google AI Studio (Veo 3)
1. Go to [Google AI Studio](https://aistudio.google.com/)
2. Sign in with your Google account
3. Navigate to "Video Generation" or "Veo"
4. Enter this prompt: `{prompt}`
5. Set aspect ratio to 9:16 (vertical for YouTube Shorts)
6. Generate and download the video
7. Save as: `veo3_video_{timestamp}.mp4`

### Option 2: Alternative AI Video Tools
- RunwayML
- Pika Labs
- Luma AI
- Stable Video Diffusion

### Option 3: Quick Manual Creation
1. Use Canva or similar tool
2. Create vertical (9:16) video template
3. Add text overlay with the prompt concept
4. Use stock footage related to: {prompt}
5. Export as MP4 for YouTube Shorts

## 📁 File Location
Save the final video as: `{os.path.join(tempfile.gettempdir(), f'manual_video_{timestamp}.mp4')}`

## 🚀 Next Steps
After creating the video manually:
1. Place it in the temp directory with the filename above
2. Continue with YouTube upload

---
*This file was auto-generated by the AI Video Automation Pipeline*
"""
        instructions_path = os.path.join(tempfile.gettempdir(), instructions_file)
        async with aiofiles.open(instructions_path, 'w') as f:
            await f.write(instructions)
        logger.info(f"Manual video instructions created: {instructions_path}")
    except Exception as e:
        logger.error(f"Failed to create manual instructions: {e}")
